[[navbar]]
identifier = "about"
name = "Chi siamo"
url = "/it/"
weight = 1
[[navbar]]
identifier = "news"
name = "Novità"
url = "/it/news/"
weight = 2
[[navbar]]
identifier = "writeups"
name = "Writeups"
url = "/it/writeups/"
weight = 3
[[navbar]]
identifier = "contacts"
name = "Contatti"
url = "/it/Contacts/"
weight = 4
